import 'models.dart';

typedef TranslationMap = Map<String, String>;

class AppLocalizations {
  AppLocalizations(this.language);

  final AppLanguage language;

  static const TranslationMap _base = {
    'app.name': 'CIVICSETU',
    'app.tagline': 'Empowering citizens. Building better India.',
    'common.logout': 'Logout',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.submit': 'Submit',
    'common.profile': 'Profile',
    'common.details': 'Details',
    'common.location': 'Location',
    'common.address': 'Address',
    'common.status': 'Status',
    'common.category': 'Category',
    'common.comments': 'Comments',
    'common.noComments': 'No comments yet.',
    'common.addComment': 'Add comment',
    'common.viewDetails': 'View details',
    'common.pickImage': 'Pick image',
    'common.useSample': 'Use sample image',
    'common.refresh': 'Refresh',
    'common.language': 'Language',
    'common.state': 'State',
    'common.city': 'City',
    'common.up': 'Up',
    'common.down': 'Down',
    'common.reportedOn': 'Reported On',
    'common.raisedCount': 'Raised {count}x',
    'common.communityRating': 'Community Rating',
    'common.resolutionProof': 'Resolution Proof',
    'common.beforeAfter': 'Before & After',
    'common.pending': 'Pending',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.analytics': 'Analytics',
    'common.issueCount': '{count} issues',
    'common.projectCount': '{count} projects',
    'common.requestCount': '{count} requests',
    'common.contributionCount': '{count} contributions',
    'common.active': 'Active',
    'common.resolved': 'Resolved',
    'common.total': 'Total',
    'camera.open': 'Quick Camera',
    'camera.geoFetch': 'Geo Fetch',
    'camera.geoFetchAlwaysOn': 'Geo-fetch always on',
    'camera.initializing': 'Opening in-app camera...',
    'camera.unavailable': 'Camera is unavailable on this device right now.',
    'camera.captureHelp':
        'Capture the complaint photo here and we will attach it to your manual complaint with auto-fetched location.',
    'camera.refreshLocation': 'Refresh Location',
    'camera.detectingLocation': 'Fetching live location...',
    'camera.locationReady': 'Location ready',
    'camera.captureFailed': 'Photo capture failed. Please try again.',
    'camera.draftReady':
        'Photo captured. Complete the complaint details manually and submit when ready.',
    'camera.photoAttached': 'Photo attached successfully.',
    'status.open_for_bidding': 'Open for Bidding',
    'status.in_progress': 'In Progress',
    'status.awaiting_citizen_verification': 'Awaiting Citizen Verification',
    'status.resolved': 'Resolved',
    'category.road': 'Road',
    'category.water': 'Water',
    'category.electricity': 'Electricity',
    'category.sanitation': 'Sanitation',
    'urgency.high': 'High',
    'urgency.medium': 'Medium',
    'urgency.low': 'Low',
    'landing.badge': 'Active Across Multiple Indian States',
    'landing.citizen': 'Citizen Login',
    'landing.authority': 'Authority Login',
    'landing.contractor': 'Contractor Login',
    'landing.ngo': 'NGO Login',
    'landing.enter': 'Enter Portal',
    'landing.donate': 'Donate to NGO',
    'landing.stats.resolved': 'Issues Resolved',
    'landing.stats.states': 'States Covered',
    'landing.stats.ngos': 'Active NGOs',
    'landing.stats.contractors': 'Contractors',
    'citizen.title': 'Citizen Portal',
    'citizen.issues': 'My Issues',
    'citizen.report': 'Report',
    'citizen.chat': 'Chat',
    'citizen.profile': 'Profile',
    'citizen.newIssue': 'Report a New Issue',
    'citizen.issueTitle': 'Issue Title',
    'citizen.description': 'Description',
    'citizen.voiceMode': 'Voice Mode',
    'citizen.typeMode': 'Type Mode',
    'citizen.autoLocation': 'Auto Location',
    'citizen.useCurrentLocation': 'Use Current Location',
    'citizen.detectingLocation': 'Detecting location...',
    'citizen.locationReady': 'OpenStreetMap preview ready',
    'citizen.locationHelp':
        'Use your current location to prefill nearby address details.',
    'citizen.startRecording': 'Start Recording',
    'citizen.stopRecording': 'Stop Recording',
    'citizen.recording': 'Recording...',
    'citizen.processing': 'Processing voice...',
    'citizen.voiceConverted': 'Voice converted successfully.',
    'citizen.voiceFailed': 'Voice not clear. Please try again.',
    'citizen.submitIssue': 'Submit Issue',
    'citizen.duplicateMerged':
        'Same issue already exists at this location. Raised count updated to {count}x.',
    'citizen.submitted': 'Issue submitted successfully.',
    'citizen.verifyClose': 'Verify and Close Issue',
    'citizen.notSolved': 'Not Solved Yet',
    'citizen.rateExperience': 'Rate your experience',
    'citizen.support': 'CIVICSETU Support',
    'citizen.messagePlaceholder': 'Type your message...',
    'citizen.noIssues': 'No issues found.',
    'authority.title': 'Authority Portal',
    'authority.dashboard': 'Dashboard',
    'authority.issues': 'All Issues',
    'authority.bids': 'Contractor Bids',
    'authority.ngo': 'NGO Requests',
    'authority.quality': 'State Quality Rankings',
    'authority.bestPerformer': 'Best performer',
    'authority.uploadProof': 'Upload resolution proof',
    'authority.freezeApprove': 'Approve review batch',
    'authority.freezeReject': 'Reject review batch',
    'authority.selectBid': 'Select bid',
    'contractor.title': 'Contractor Portal',
    'contractor.bids': 'Open Bids',
    'contractor.projects': 'My Projects',
    'contractor.profile': 'Profile',
    'contractor.submitBid': 'Submit bid',
    'contractor.uploadCompletion': 'Upload completion image',
    'ngo.title': 'NGO Portal',
    'ngo.issues': 'Unresolved Issues',
    'ngo.requests': 'My Requests',
    'ngo.analytics': 'Analytics',
    'ngo.donations': 'Donations',
    'ngo.raiseRequest': 'Raise Request',
    'ngo.addDonation': 'Add Donation',
    'ngo.totalDonations': 'Total Donations Received',
    'msg.permissionDenied': 'Permission was denied on this device.',
    'msg.locationServiceDisabled':
        'Turn on device location services to geo-fetch the complaint spot.',
    'msg.locationUnavailable': 'Location could not be detected.',
  };

  static const Map<AppLanguage, TranslationMap> _overrides = {
    AppLanguage.en: {},
    AppLanguage.hi: {
      'app.name': 'सिविकसेतु',
      'app.tagline': 'नागरिकों को सशक्त बनाना, बेहतर भारत बनाना।',
      'common.logout': 'लॉग आउट',
      'common.cancel': 'रद्द करें',
      'common.submit': 'जमा करें',
      'common.profile': 'प्रोफ़ाइल',
      'common.details': 'विवरण',
      'common.location': 'स्थान',
      'common.address': 'पता',
      'common.status': 'स्थिति',
      'common.category': 'श्रेणी',
      'common.comments': 'टिप्पणियां',
      'common.noComments': 'अभी कोई टिप्पणी नहीं है।',
      'common.addComment': 'टिप्पणी जोड़ें',
      'common.viewDetails': 'विवरण देखें',
      'common.pickImage': 'चित्र चुनें',
      'common.language': 'भाषा',
      'common.state': 'राज्य',
      'common.city': 'शहर',
      'common.up': 'समर्थन',
      'common.down': 'विरोध',
      'common.reportedOn': 'रिपोर्ट की तिथि',
      'common.communityRating': 'सामुदायिक रेटिंग',
      'common.resolutionProof': 'समाधान प्रमाण',
      'common.beforeAfter': 'पहले और बाद की तुलना',
      'common.pending': 'लंबित',
      'common.approved': 'स्वीकृत',
      'common.rejected': 'अस्वीकृत',
      'common.analytics': 'विश्लेषण',
      'common.active': 'सक्रिय',
      'common.resolved': 'समाधान हो चुका है',
      'common.total': 'कुल',
      'status.open_for_bidding': 'बोली के लिए खुला',
      'status.in_progress': 'कार्य प्रगति पर',
      'status.awaiting_citizen_verification': 'नागरिक सत्यापन लंबित',
      'status.resolved': 'समाधान हो चुका है',
      'category.road': 'सड़क',
      'category.water': 'पानी',
      'category.electricity': 'बिजली',
      'category.sanitation': 'स्वच्छता',
      'urgency.high': 'उच्च',
      'urgency.medium': 'मध्यम',
      'urgency.low': 'कम',
      'landing.badge': 'कई भारतीय राज्यों में सक्रिय',
      'landing.citizen': 'नागरिक लॉगिन',
      'landing.authority': 'प्राधिकरण लॉगिन',
      'landing.contractor': 'ठेकेदार लॉगिन',
      'landing.ngo': 'एनजीओ लॉगिन',
      'landing.enter': 'पोर्टल में प्रवेश करें',
      'landing.donate': 'एनजीओ को दान दें',
      'citizen.title': 'नागरिक पोर्टल',
      'citizen.issues': 'मेरी समस्याएं',
      'citizen.report': 'रिपोर्ट',
      'citizen.chat': 'चैट',
      'citizen.profile': 'प्रोफ़ाइल',
      'citizen.newIssue': 'नई समस्या दर्ज करें',
      'citizen.issueTitle': 'समस्या शीर्षक',
      'citizen.description': 'विवरण',
      'citizen.voiceMode': 'वॉइस मोड',
      'citizen.typeMode': 'टाइप मोड',
      'citizen.autoLocation': 'ऑटो लोकेशन',
      'citizen.useCurrentLocation': 'वर्तमान स्थान उपयोग करें',
      'citizen.detectingLocation': 'स्थान पता किया जा रहा है...',
      'citizen.locationReady': 'ओपनस्ट्रीटमैप पूर्वावलोकन तैयार है',
      'citizen.startRecording': 'रिकॉर्डिंग शुरू करें',
      'citizen.stopRecording': 'रिकॉर्डिंग बंद करें',
      'citizen.recording': 'रिकॉर्डिंग चल रही है...',
      'citizen.processing': 'वॉइस प्रोसेस हो रही है...',
      'citizen.submitIssue': 'समस्या जमा करें',
      'citizen.verifyClose': 'सत्यापित करें और बंद करें',
      'citizen.notSolved': 'अभी हल नहीं हुआ',
      'citizen.rateExperience': 'अपना अनुभव रेट करें',
      'authority.title': 'प्राधिकरण पोर्टल',
      'authority.dashboard': 'डैशबोर्ड',
      'authority.issues': 'सभी समस्याएं',
      'authority.bids': 'ठेकेदार बोलियां',
      'authority.ngo': 'एनजीओ अनुरोध',
      'contractor.title': 'ठेकेदार पोर्टल',
      'contractor.bids': 'खुली बोलियां',
      'contractor.projects': 'मेरे प्रोजेक्ट',
      'ngo.title': 'एनजीओ पोर्टल',
      'ngo.issues': 'अनसुलझी समस्याएं',
      'ngo.requests': 'मेरे अनुरोध',
      'ngo.analytics': 'विश्लेषण',
      'ngo.donations': 'दान',
    },
    AppLanguage.ta: {
      'app.name': 'சிவிக்சேது',
      'common.logout': 'வெளியேறு',
      'common.cancel': 'ரத்து செய்',
      'common.submit': 'சமர்ப்பிக்கவும்',
      'common.profile': 'சுயவிவரம்',
      'common.details': 'விவரங்கள்',
      'common.location': 'இடம்',
      'common.address': 'முகவரி',
      'common.status': 'நிலை',
      'common.category': 'வகை',
      'common.comments': 'கருத்துகள்',
      'status.open_for_bidding': 'ஏலத்திற்கு திறந்தது',
      'status.in_progress': 'நடைமுறையில் உள்ளது',
      'status.awaiting_citizen_verification':
          'குடிமக்கள் உறுதிப்படுத்தல் நிலுவையில்',
      'status.resolved': 'தீர்க்கப்பட்டது',
      'category.road': 'சாலை',
      'category.water': 'நீர்',
      'category.electricity': 'மின்சாரம்',
      'category.sanitation': 'சுத்தம்',
      'citizen.title': 'குடிமக்கள் போர்டல்',
      'authority.title': 'அதிகாரி போர்டல்',
      'contractor.title': 'ஒப்பந்ததாரர் போர்டல்',
      'ngo.title': 'என்ஜிஓ போர்டல்',
    },
    AppLanguage.mr: {
      'app.name': 'सिविकसेतु',
      'common.logout': 'लॉग आउट',
      'common.cancel': 'रद्द करा',
      'common.submit': 'सबमिट करा',
      'common.profile': 'प्रोफाइल',
      'common.details': 'तपशील',
      'common.location': 'स्थान',
      'common.address': 'पत्ता',
      'common.status': 'स्थिती',
      'common.category': 'श्रेणी',
      'status.open_for_bidding': 'बोलीसाठी खुले',
      'status.in_progress': 'काम सुरू आहे',
      'status.awaiting_citizen_verification': 'नागरिक पडताळणी प्रलंबित',
      'status.resolved': 'निकाली निघाले',
      'category.road': 'रस्ता',
      'category.water': 'पाणी',
      'category.electricity': 'वीज',
      'category.sanitation': 'स्वच्छता',
      'citizen.title': 'नागरिक पोर्टल',
      'authority.title': 'प्राधिकरण पोर्टल',
      'contractor.title': 'कंत्राटदार पोर्टल',
      'ngo.title': 'एनजीओ पोर्टल',
    },
    AppLanguage.kn: {
      'app.name': 'ಸಿವಿಕ್‌ಸೇತು',
      'common.logout': 'ಲಾಗ್ ಔಟ್',
      'common.cancel': 'ರದ್ದುಮಾಡಿ',
      'common.submit': 'ಸಲ್ಲಿಸಿ',
      'common.profile': 'ಪ್ರೊಫೈಲ್',
      'common.details': 'ವಿವರಗಳು',
      'common.location': 'ಸ್ಥಳ',
      'common.address': 'ವಿಳಾಸ',
      'common.status': 'ಸ್ಥಿತಿ',
      'common.category': 'ವರ್ಗ',
      'status.open_for_bidding': 'ಬಿಡ್ಡಿಂಗ್‌ಗೆ ತೆರೆಯಲಾಗಿದೆ',
      'status.in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'status.awaiting_citizen_verification': 'ನಾಗರಿಕ ಪರಿಶೀಲನೆ ಬಾಕಿ',
      'status.resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
      'category.road': 'ರಸ್ತೆ',
      'category.water': 'ನೀರು',
      'category.electricity': 'ವಿದ್ಯುತ್',
      'category.sanitation': 'ಸ್ವಚ್ಛತೆ',
      'citizen.title': 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
      'authority.title': 'ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್',
      'contractor.title': 'ಕಾಂಟ್ರಾಕ್ಟರ್ ಪೋರ್ಟಲ್',
      'ngo.title': 'ಎನ್‌ಜಿಒ ಪೋರ್ಟಲ್',
    },
  };

  static const Map<AppLanguage, Map<String, String>> _stateNames = {
    AppLanguage.hi: {
      'Delhi': 'दिल्ली',
      'Maharashtra': 'महाराष्ट्र',
      'Karnataka': 'कर्नाटक',
      'Tamil Nadu': 'तमिलनाडु',
      'Gujarat': 'गुजरात',
      'Rajasthan': 'राजस्थान',
      'Telangana': 'तेलंगाना',
      'West Bengal': 'पश्चिम बंगाल',
    },
    AppLanguage.ta: {
      'Delhi': 'டெல்லி',
      'Maharashtra': 'மகாராஷ்டிரா',
      'Karnataka': 'கர்நாடகா',
      'Tamil Nadu': 'தமிழ்நாடு',
      'Gujarat': 'குஜராத்',
      'Rajasthan': 'ராஜஸ்தான்',
      'Telangana': 'தெலங்கானா',
      'West Bengal': 'மேற்கு வங்காளம்',
    },
    AppLanguage.mr: {
      'Delhi': 'दिल्ली',
      'Maharashtra': 'महाराष्ट्र',
      'Karnataka': 'कर्नाटक',
      'Tamil Nadu': 'तामिळनाडू',
      'Gujarat': 'गुजरात',
      'Rajasthan': 'राजस्थान',
      'Telangana': 'तेलंगणा',
      'West Bengal': 'पश्चिम बंगाल',
    },
    AppLanguage.kn: {
      'Delhi': 'ದೆಹಲಿ',
      'Maharashtra': 'ಮಹಾರಾಷ್ಟ್ರ',
      'Karnataka': 'ಕರ್ನಾಟಕ',
      'Tamil Nadu': 'ತಮಿಳುನಾಡು',
      'Gujarat': 'ಗುಜರಾತ್',
      'Rajasthan': 'ರಾಜಸ್ಥಾನ್',
      'Telangana': 'ತೆಲಂಗಾಣ',
      'West Bengal': 'ಪಶ್ಚಿಮ ಬಂಗಾಳ',
    },
  };

  String t(String key, [Map<String, Object?> params = const {}]) {
    final dictionary = {..._base, ...?_overrides[language]};
    var value = dictionary[key] ?? key;
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', '$paramValue');
    });
    return value;
  }

  String categoryLabel(IssueCategory category) => t('category.${category.key}');

  String statusLabel(IssueStatus status) => t('status.${status.key}');

  String urgencyLabel(UrgencyTag tag) => t('urgency.${tag.key}');

  String roleLabel(UserRole role) => switch (role) {
        UserRole.citizen => t('landing.citizen'),
        UserRole.authority => t('landing.authority'),
        UserRole.contractor => t('landing.contractor'),
        UserRole.ngo => t('landing.ngo'),
      };

  String stateName(String state) {
    if (language == AppLanguage.en) {
      return state;
    }
    return _stateNames[language]?[state] ?? state;
  }
}
